# Generated by Django 5.2.14 on 2026-05-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GGUFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField()),
                ('n_ctx', models.PositiveIntegerField(default=2048)),
                ('n_gpu_layers', models.PositiveIntegerField(default=0)),
                ('n_threads', models.PositiveIntegerField(blank=True, null=True)),
                ('seed', models.IntegerField(default=-1)),
            ],
            options={
                'db_table': 'gguf_models',
            },
        ),
    ]
