# Generated by Django 5.2.14 on 2026-05-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ggufmodel',
            name='type',
            field=models.CharField(choices=[('chat', 'Chat'), ('embedding', 'Embedding')], default='chat', max_length=20),
        ),
    ]
